# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_service import structure_pb2 as grpc__service_dot_structure__pb2


class CheckServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendCheck = channel.unary_unary(
                '/CheckService/SendCheck',
                request_serializer=grpc__service_dot_structure__pb2.Check.SerializeToString,
                response_deserializer=grpc__service_dot_structure__pb2.Response.FromString,
                )


class CheckServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CheckServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCheck,
                    request_deserializer=grpc__service_dot_structure__pb2.Check.FromString,
                    response_serializer=grpc__service_dot_structure__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CheckService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CheckService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CheckService/SendCheck',
            grpc__service_dot_structure__pb2.Check.SerializeToString,
            grpc__service_dot_structure__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
